// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEcrAC-eYnw9hTaXdEK-xTbd4ySWjb9U4',
    appId: '1:11539579120:web:7e147af39c556b13f00235',
    messagingSenderId: '11539579120',
    projectId: 'hope-ca563',
    authDomain: 'hope-ca563.firebaseapp.com',
    storageBucket: 'hope-ca563.appspot.com',
    measurementId: 'G-BKHZ1HJHWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDfjLSatcNTYaWKlNF8g1-jgwYJR0cz_Q',
    appId: '1:11539579120:android:e582ecb583f0a86bf00235',
    messagingSenderId: '11539579120',
    projectId: 'hope-ca563',
    storageBucket: 'hope-ca563.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ToO5COnN3RaZ9HzMRcPynz15St0pRiE',
    appId: '1:11539579120:ios:8654682adbb06956f00235',
    messagingSenderId: '11539579120',
    projectId: 'hope-ca563',
    storageBucket: 'hope-ca563.appspot.com',
    iosClientId: '11539579120-b52b1lhd9l6sfvdh7jii35bdhv2ugc8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.hope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ToO5COnN3RaZ9HzMRcPynz15St0pRiE',
    appId: '1:11539579120:ios:a1dfbde5f8be5638f00235',
    messagingSenderId: '11539579120',
    projectId: 'hope-ca563',
    storageBucket: 'hope-ca563.appspot.com',
    iosClientId: '11539579120-ic6h498mm80lsbce9q06ejhh0sv5ba64.apps.googleusercontent.com',
    iosBundleId: 'com.example.hope.RunnerTests',
  );
}
